-- RBAC foundation for admin accounts.
-- Review and execute only after the confirmed Production project is selected.
-- This migration is intentionally additive and keeps admin_profiles.role for compatibility.

-- Fail before creating RBAC objects if the verified bootstrap identity has drifted.
do $$
declare
  bootstrap_user_id constant uuid := '2dfd1ab1-1fe2-4024-91bc-b17103f524be';
  auth_user_count integer;
  profile_count integer;
  profile_role text;
  profile_name text;
  profile_role_key text;
  profile_is_active text;
begin
  select count(*) into auth_user_count
  from auth.users
  where id = bootstrap_user_id;

  if auth_user_count <> 1 then
    raise exception 'RBAC preflight aborted: expected exactly one verified Auth user, found %', auth_user_count;
  end if;

  select count(*) into profile_count
  from public.admin_profiles
  where user_id = bootstrap_user_id;

  if profile_count <> 1 then
    raise exception 'RBAC preflight aborted: expected exactly one admin profile for the verified Auth user, found %', profile_count;
  end if;

  select p.role, p.display_name, to_jsonb(p)->>'role_key', to_jsonb(p)->>'is_active'
  into profile_role, profile_name, profile_role_key, profile_is_active
  from public.admin_profiles p
  where p.user_id = bootstrap_user_id;

  if lower(trim(coalesce(profile_name, ''))) <> 'fathy'
     or lower(trim(coalesce(profile_role, ''))) <> 'admin' then
    raise exception 'RBAC preflight aborted: verified profile is not the expected legacy admin';
  end if;

  if profile_role_key is not null and profile_role_key <> 'super_admin' then
    raise exception 'RBAC preflight aborted: verified profile already has a conflicting role_key';
  end if;

  if profile_is_active = 'false' then
    raise exception 'RBAC preflight aborted: verified profile is already inactive';
  end if;
end
$$;

-- Validate only legacy prerequisites before DDL. Fresh installs may have none of
-- the RBAC tables yet, so optional RBAC objects are inspected through catalogs.
do $$
declare
  rbac_table_count integer;
  existing_rbac_tables text;
begin
  select count(*), string_agg(c.relname, ', ' order by c.relname)
  into rbac_table_count, existing_rbac_tables
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relkind in ('r', 'p')
    and c.relname in (
      'admin_roles', 'admin_permissions', 'admin_role_permissions',
      'admin_permission_overrides', 'admin_audit_logs'
    );

  if rbac_table_count <> 0 then
    raise exception 'RBAC preflight aborted: partial RBAC state detected (% of 5 tables: %)',
      rbac_table_count, existing_rbac_tables;
  end if;
end
$$;

create table if not exists public.admin_roles (
  key text primary key,
  name text not null,
  description text,
  is_system boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_permissions (
  key text primary key,
  name text not null,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_role_permissions (
  role_key text not null references public.admin_roles(key) on delete cascade,
  permission_key text not null references public.admin_permissions(key) on delete cascade,
  primary key (role_key, permission_key)
);

create table if not exists public.admin_permission_overrides (
  -- Overrides are per-user dependent data; audit history uses SET NULL and is retained.
  user_id uuid not null references auth.users(id) on delete cascade,
  permission_key text not null references public.admin_permissions(key) on delete cascade,
  effect text not null check (effect in ('allow', 'deny')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, permission_key)
);

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  permission_key text,
  entity_type text,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  request_id text,
  ip_hash text,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.admin_profiles add column if not exists role_key text;
alter table public.admin_profiles add column if not exists is_active boolean not null default true;
alter table public.admin_profiles add column if not exists last_login_at timestamptz;
alter table public.admin_profiles add column if not exists created_by uuid;
alter table public.admin_profiles add column if not exists updated_at timestamptz not null default now();

do $$
declare
  v record;
  foreign_key_count integer;
  exact_foreign_key_count integer;
begin
  for v in
    select * from (values
      ('role_key', 'public.admin_roles', 'key', 'r', 'admin_profiles_role_key_fkey'),
      ('created_by', 'auth.users', 'id', 'n', 'admin_profiles_created_by_fkey'),
      ('user_id', 'auth.users', 'id', 'r', 'admin_profiles_user_id_fkey')
    ) as expected(source_column, target_table, target_column, delete_action, constraint_name)
  loop
    select count(*) into foreign_key_count
    from pg_constraint c
    join pg_attribute source_column
      on source_column.attrelid = c.conrelid and source_column.attname = v.source_column
    where c.conrelid = 'public.admin_profiles'::regclass
      and c.contype = 'f'
      and source_column.attnum = any(c.conkey);

    select count(*) into exact_foreign_key_count
    from pg_constraint c
    join pg_attribute source_column
      on source_column.attrelid = c.conrelid and source_column.attname = v.source_column
    join pg_attribute target_column
      on target_column.attrelid = c.confrelid and target_column.attname = v.target_column
    where c.conrelid = 'public.admin_profiles'::regclass
      and c.contype = 'f'
      and c.conkey = array[source_column.attnum]::smallint[]
      and c.confrelid = to_regclass(v.target_table)
      and c.confkey = array[target_column.attnum]::smallint[]
      and (v.source_column = 'user_id' or c.confdeltype = v.delete_action)
      and c.convalidated;

    if foreign_key_count = 0 then
      execute format(
        'alter table public.admin_profiles add constraint %I foreign key (%I) references %s(%I) on delete %s',
        v.constraint_name,
        v.source_column,
        v.target_table,
        v.target_column,
        case v.delete_action when 'r' then 'restrict' when 'n' then 'set null' end
      );
    elsif foreign_key_count <> 1 or exact_foreign_key_count <> 1 then
      raise exception 'RBAC schema preflight aborted: conflicting foreign key on admin_profiles.%', v.source_column;
    end if;
  end loop;
end
$$;

-- Validate the complete schema after creating or extending its objects.
do $$
declare
  v record;
  actual_type text;
  actual_not_null boolean;
  actual_default text;
  actual_identity text;
  primary_key_count integer;
  actual_key_columns text[];
  exact_foreign_key_count integer;
begin
  for v in
    select unnest(array[
      'public.admin_roles',
      'public.admin_permissions',
      'public.admin_role_permissions',
      'public.admin_permission_overrides',
      'public.admin_audit_logs'
    ]) as table_name
  loop
    if to_regclass(v.table_name) is null then
      raise exception 'RBAC post-DDL validation failed: table % is missing', v.table_name;
    end if;
  end loop;

  for v in
    select * from (values
      ('public.admin_profiles', 'user_id', 'uuid', null::boolean),
      ('public.admin_profiles', 'role', 'text', null::boolean),
      ('public.admin_profiles', 'display_name', 'text', null::boolean),
      ('public.admin_profiles', 'created_at', 'timestamp with time zone', true),
      ('public.admin_profiles', 'role_key', 'text', false),
      ('public.admin_profiles', 'is_active', 'boolean', true),
      ('public.admin_profiles', 'last_login_at', 'timestamp with time zone', false),
      ('public.admin_profiles', 'created_by', 'uuid', false),
      ('public.admin_profiles', 'updated_at', 'timestamp with time zone', true),
      ('public.admin_roles', 'key', 'text', true),
      ('public.admin_roles', 'name', 'text', true),
      ('public.admin_roles', 'description', 'text', false),
      ('public.admin_roles', 'is_system', 'boolean', true),
      ('public.admin_roles', 'created_at', 'timestamp with time zone', true),
      ('public.admin_permissions', 'key', 'text', true),
      ('public.admin_permissions', 'name', 'text', true),
      ('public.admin_permissions', 'description', 'text', false),
      ('public.admin_permissions', 'created_at', 'timestamp with time zone', true),
      ('public.admin_role_permissions', 'role_key', 'text', true),
      ('public.admin_role_permissions', 'permission_key', 'text', true),
      ('public.admin_permission_overrides', 'user_id', 'uuid', true),
      ('public.admin_permission_overrides', 'permission_key', 'text', true),
      ('public.admin_permission_overrides', 'effect', 'text', true),
      ('public.admin_permission_overrides', 'created_at', 'timestamp with time zone', true),
      ('public.admin_permission_overrides', 'updated_at', 'timestamp with time zone', true),
      ('public.admin_audit_logs', 'id', 'bigint', true),
      ('public.admin_audit_logs', 'actor_user_id', 'uuid', false),
      ('public.admin_audit_logs', 'action', 'text', true),
      ('public.admin_audit_logs', 'permission_key', 'text', false),
      ('public.admin_audit_logs', 'entity_type', 'text', false),
      ('public.admin_audit_logs', 'entity_id', 'text', false),
      ('public.admin_audit_logs', 'metadata', 'jsonb', true),
      ('public.admin_audit_logs', 'request_id', 'text', false),
      ('public.admin_audit_logs', 'ip_hash', 'text', false),
      ('public.admin_audit_logs', 'user_agent', 'text', false),
      ('public.admin_audit_logs', 'created_at', 'timestamp with time zone', true)
    ) as expected(table_name, column_name, type_name, not_null)
  loop
    select format_type(a.atttypid, a.atttypmod), a.attnotnull
    into actual_type, actual_not_null
    from pg_attribute a
    where a.attrelid = to_regclass(v.table_name)
      and a.attname = v.column_name
      and a.attnum > 0
      and not a.attisdropped;

    if not found
       or actual_type <> v.type_name
       or (v.not_null is not null and actual_not_null <> v.not_null) then
      raise exception 'RBAC post-DDL validation failed: incompatible column %.%', v.table_name, v.column_name;
    end if;
  end loop;

  for v in
    select * from (values
      ('public.admin_profiles', 'is_active', 'true'),
      ('public.admin_profiles', 'updated_at', 'now'),
      ('public.admin_profiles', 'created_at', 'now'),
      ('public.admin_roles', 'is_system', 'true'),
      ('public.admin_roles', 'created_at', 'now'),
      ('public.admin_permissions', 'created_at', 'now'),
      ('public.admin_permission_overrides', 'created_at', 'now'),
      ('public.admin_permission_overrides', 'updated_at', 'now'),
      ('public.admin_audit_logs', 'metadata', '''{}''::jsonb'),
      ('public.admin_audit_logs', 'created_at', 'now')
    ) as expected(table_name, column_name, default_expression)
  loop
    select pg_get_expr(d.adbin, d.adrelid)
    into actual_default
    from pg_attribute a
    left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
    where a.attrelid = to_regclass(v.table_name)
      and a.attname = v.column_name
      and a.attnum > 0
      and not a.attisdropped;

    if not found
       or actual_default is null
       or regexp_replace(lower(actual_default), '[[:space:]()]', '', 'g') <> v.default_expression then
      raise exception 'RBAC post-DDL validation failed: incompatible default on %.%', v.table_name, v.column_name;
    end if;
  end loop;

  select a.attidentity into actual_identity
  from pg_attribute a
  where a.attrelid = 'public.admin_audit_logs'::regclass
    and a.attname = 'id'
    and a.attnum > 0
    and not a.attisdropped;

  if actual_identity <> 'd' then
    raise exception 'RBAC post-DDL validation failed: admin_audit_logs.id must be GENERATED BY DEFAULT AS IDENTITY';
  end if;

  for v in
    select * from (values
      ('public.admin_roles', array['key']::text[]),
      ('public.admin_permissions', array['key']::text[]),
      ('public.admin_role_permissions', array['role_key', 'permission_key']::text[]),
      ('public.admin_permission_overrides', array['user_id', 'permission_key']::text[]),
      ('public.admin_audit_logs', array['id']::text[])
    ) as expected(table_name, key_columns)
  loop
    select count(*) into primary_key_count
    from pg_constraint c
    where c.conrelid = to_regclass(v.table_name) and c.contype = 'p';

    select array_agg(a.attname::text order by k.ordinality) into actual_key_columns
    from pg_constraint c
    cross join lateral unnest(c.conkey) with ordinality as k(attnum, ordinality)
    join pg_attribute a on a.attrelid = c.conrelid and a.attnum = k.attnum
    where c.conrelid = to_regclass(v.table_name) and c.contype = 'p';

    if primary_key_count <> 1 or actual_key_columns is distinct from v.key_columns then
      raise exception 'RBAC post-DDL validation failed: incompatible primary key on %', v.table_name;
    end if;
  end loop;

  for v in
    select * from (values
      ('public.admin_role_permissions', 'role_key', 'public.admin_roles', 'key', 'c'),
      ('public.admin_role_permissions', 'permission_key', 'public.admin_permissions', 'key', 'c'),
      ('public.admin_permission_overrides', 'user_id', 'auth.users', 'id', 'c'),
      ('public.admin_permission_overrides', 'permission_key', 'public.admin_permissions', 'key', 'c'),
      ('public.admin_audit_logs', 'actor_user_id', 'auth.users', 'id', 'n')
    ) as expected(source_table, source_column, target_table, target_column, delete_action)
  loop
    select count(*) into exact_foreign_key_count
    from pg_constraint c
    join pg_attribute source_column
      on source_column.attrelid = c.conrelid and source_column.attname = v.source_column
    join pg_attribute target_column
      on target_column.attrelid = c.confrelid and target_column.attname = v.target_column
    where c.conrelid = to_regclass(v.source_table)
      and c.contype = 'f'
      and c.conkey = array[source_column.attnum]::smallint[]
      and c.confrelid = to_regclass(v.target_table)
      and c.confkey = array[target_column.attnum]::smallint[]
      and c.confdeltype = v.delete_action
      and c.convalidated;

    if exact_foreign_key_count <> 1 then
      raise exception 'RBAC post-DDL validation failed: incompatible foreign key on %.%', v.source_table, v.source_column;
    end if;
  end loop;

  if not exists (
    select 1
    from pg_constraint c
    join pg_attribute a on a.attrelid = c.conrelid and a.attname = 'effect'
    where c.conrelid = 'public.admin_permission_overrides'::regclass
      and c.contype = 'c'
      and a.attnum = any(c.conkey)
      and position('allow' in pg_get_constraintdef(c.oid)) > 0
      and position('deny' in pg_get_constraintdef(c.oid)) > 0
  ) then
    raise exception 'RBAC post-DDL validation failed: missing allow/deny constraint';
  end if;
end
$$;

insert into public.admin_roles (key, name, description)
values
  ('super_admin', 'المدير العام', 'Full system administration and RBAC management.'),
  ('supervisor', 'المشرف العام', 'Operational oversight without admin-account or global-settings changes.'),
  ('match_manager', 'مسؤول المباريات والنتائج', 'Matches, schedules, live operations, results, and match statistics.'),
  ('registration_manager', 'مسؤول التسجيل والقوائم', 'Team registrations, rosters, players, documents, and approvals.'),
  ('tournament_manager', 'مسؤول البطولات', 'Tournaments, teams, groups, and tournament registration settings.'),
  ('content_manager', 'مسؤول الإعلام والمحتوى', 'News, content, publishing, and notifications.'),
  ('shop_manager', 'مسؤول المتجر', 'Products and operational order management.'),
  ('viewer', 'مراقب', 'Read-only access to permitted operational areas.')
on conflict (key) do nothing;

insert into public.admin_permissions (key, name, description)
values
  ('dashboard.view', 'View dashboard', 'View the administration dashboard.'),
  ('matches.view', 'View matches', 'View matches and match details.'),
  ('matches.create', 'Create matches', 'Create matches.'),
  ('matches.edit', 'Edit matches', 'Edit match details.'),
  ('matches.delete', 'Delete matches', 'Delete matches.'),
  ('matches.schedule.manage', 'Manage match schedules', 'Manage match dates and schedules.'),
  ('matches.live.manage', 'Manage live matches', 'Manage live match state and events.'),
  ('matches.results.manage', 'Manage match results', 'Create and edit match results.'),
  ('stats.view', 'View statistics', 'View match and player statistics.'),
  ('stats.goals.manage', 'Manage goal statistics', 'Manage goal statistics.'),
  ('stats.cards.manage', 'Manage card statistics', 'Manage card statistics.'),
  ('stats.motm.manage', 'Manage player of the match', 'Manage player of the match statistics.'),
  ('stats.formations.manage', 'Manage formations', 'Manage match formations.'),
  ('stats.photos.upload', 'Upload statistics photos', 'Upload photos used by statistics.'),
  ('rosters.view', 'View rosters', 'View team rosters.'),
  ('rosters.create', 'Create rosters', 'Create team rosters.'),
  ('rosters.edit', 'Edit rosters', 'Edit team rosters.'),
  ('rosters.delete', 'Delete rosters', 'Delete team rosters.'),
  ('rosters.approve', 'Approve rosters', 'Approve submitted team rosters.'),
  ('rosters.players.manage', 'Manage roster players', 'Add, edit, and remove roster players.'),
  ('rosters.photos.upload', 'Upload roster photos', 'Upload player roster photos and documents.'),
  ('rosters.settings.manage', 'Manage roster settings', 'Manage roster-specific settings.'),
  ('rosters.restrictions.manage', 'Manage roster restrictions', 'Manage roster restrictions.'),
  ('registrations.view', 'View registrations', 'View team and player registrations.'),
  ('registrations.edit', 'Edit registrations', 'Edit registrations.'),
  ('registrations.delete', 'Delete registrations', 'Delete registrations.'),
  ('registrations.photos.upload', 'Upload registration photos', 'Upload registration photos and documents.'),
  ('registrations.print', 'Print registrations', 'Print registration records.'),
  ('teams.view', 'View teams', 'View teams.'),
  ('teams.manage', 'Manage teams', 'Create and edit teams.'),
  ('teams.access.grant', 'Grant team access', 'Grant team access to tournament workflows.'),
  ('teams.access.revoke', 'Revoke team access', 'Revoke team access from tournament workflows.'),
  ('tournaments.view', 'View tournaments', 'View tournaments.'),
  ('tournaments.manage', 'Manage tournaments', 'Create and edit tournaments.'),
  ('tournaments.groups.manage', 'Manage tournament groups', 'Manage tournament groups.'),
  ('tournaments.registration-settings.manage', 'Manage registration settings', 'Manage tournament registration settings.'),
  ('tournaments.player-cards.manage', 'Manage player cards', 'Manage tournament player cards.'),
  ('content.view', 'View content', 'View managed content.'),
  ('content.create', 'Create content', 'Create managed content.'),
  ('content.edit', 'Edit content', 'Edit managed content.'),
  ('content.delete', 'Delete content', 'Delete managed content.'),
  ('content.publish', 'Publish content', 'Publish managed content.'),
  ('notifications.send', 'Send notifications', 'Send administrative notifications.'),
  ('shop.products.view', 'View shop products', 'View shop products.'),
  ('shop.products.manage', 'Manage shop products', 'Create and edit shop products.'),
  ('shop.orders.view', 'View shop orders', 'View shop orders.'),
  ('shop.orders.manage', 'Manage shop orders', 'Manage operational order state.'),
  ('shop.orders.financial.manage', 'Manage financial order data', 'Manage financial order actions.'),
  ('admins.view', 'View administrators', 'View administrator accounts and roles.'),
  ('admins.create', 'Create administrators', 'Create administrator accounts.'),
  ('admins.edit', 'Edit administrators', 'Edit administrator accounts.'),
  ('admins.disable', 'Disable administrators', 'Enable or disable administrator accounts.'),
  ('admins.reset_password', 'Reset administrator passwords', 'Reset administrator passwords.'),
  ('admins.permissions.manage', 'Manage administrator permissions', 'Manage administrator roles and permission overrides.'),
  ('audit.view', 'View audit logs', 'View administrative audit logs.'),
  ('settings.manage', 'Manage settings', 'Manage global system settings.')
on conflict (key) do nothing;

insert into public.admin_role_permissions (role_key, permission_key)
select 'super_admin', key from public.admin_permissions
on conflict do nothing;

insert into public.admin_role_permissions (role_key, permission_key)
values
  ('supervisor', 'dashboard.view'),
  ('supervisor', 'matches.view'),
  ('supervisor', 'matches.create'),
  ('supervisor', 'matches.edit'),
  ('supervisor', 'matches.delete'),
  ('supervisor', 'matches.schedule.manage'),
  ('supervisor', 'matches.live.manage'),
  ('supervisor', 'matches.results.manage'),
  ('supervisor', 'stats.view'),
  ('supervisor', 'stats.goals.manage'),
  ('supervisor', 'stats.cards.manage'),
  ('supervisor', 'stats.motm.manage'),
  ('supervisor', 'stats.formations.manage'),
  ('supervisor', 'stats.photos.upload'),
  ('supervisor', 'rosters.view'),
  ('supervisor', 'rosters.create'),
  ('supervisor', 'rosters.edit'),
  ('supervisor', 'rosters.delete'),
  ('supervisor', 'rosters.approve'),
  ('supervisor', 'rosters.players.manage'),
  ('supervisor', 'rosters.photos.upload'),
  ('supervisor', 'rosters.settings.manage'),
  ('supervisor', 'rosters.restrictions.manage'),
  ('supervisor', 'registrations.view'),
  ('supervisor', 'registrations.edit'),
  ('supervisor', 'registrations.delete'),
  ('supervisor', 'registrations.photos.upload'),
  ('supervisor', 'registrations.print'),
  ('supervisor', 'teams.view'),
  ('supervisor', 'teams.manage'),
  ('supervisor', 'teams.access.grant'),
  ('supervisor', 'teams.access.revoke'),
  ('supervisor', 'tournaments.view'),
  ('supervisor', 'tournaments.manage'),
  ('supervisor', 'tournaments.groups.manage'),
  ('supervisor', 'tournaments.registration-settings.manage'),
  ('supervisor', 'tournaments.player-cards.manage'),
  ('supervisor', 'content.view'),
  ('supervisor', 'content.create'),
  ('supervisor', 'content.edit'),
  ('supervisor', 'content.delete'),
  ('supervisor', 'content.publish'),
  ('supervisor', 'notifications.send'),
  ('supervisor', 'shop.products.view'),
  ('supervisor', 'shop.products.manage'),
  ('supervisor', 'shop.orders.view'),
  ('supervisor', 'shop.orders.manage'),
  ('supervisor', 'admins.view'),
  ('supervisor', 'audit.view'),
  ('match_manager', 'dashboard.view'),
  ('match_manager', 'matches.view'),
  ('match_manager', 'matches.create'),
  ('match_manager', 'matches.edit'),
  ('match_manager', 'matches.delete'),
  ('match_manager', 'matches.schedule.manage'),
  ('match_manager', 'matches.live.manage'),
  ('match_manager', 'matches.results.manage'),
  ('match_manager', 'stats.view'),
  ('match_manager', 'stats.goals.manage'),
  ('match_manager', 'stats.cards.manage'),
  ('match_manager', 'stats.motm.manage'),
  ('match_manager', 'stats.formations.manage'),
  ('match_manager', 'stats.photos.upload'),
  ('registration_manager', 'dashboard.view'),
  ('registration_manager', 'rosters.view'),
  ('registration_manager', 'rosters.create'),
  ('registration_manager', 'rosters.edit'),
  ('registration_manager', 'rosters.delete'),
  ('registration_manager', 'rosters.approve'),
  ('registration_manager', 'rosters.players.manage'),
  ('registration_manager', 'rosters.photos.upload'),
  ('registration_manager', 'rosters.settings.manage'),
  ('registration_manager', 'rosters.restrictions.manage'),
  ('registration_manager', 'registrations.view'),
  ('registration_manager', 'registrations.edit'),
  ('registration_manager', 'registrations.delete'),
  ('registration_manager', 'registrations.photos.upload'),
  ('registration_manager', 'registrations.print'),
  ('registration_manager', 'teams.view'),
  ('tournament_manager', 'dashboard.view'),
  ('tournament_manager', 'teams.view'),
  ('tournament_manager', 'teams.manage'),
  ('tournament_manager', 'teams.access.grant'),
  ('tournament_manager', 'teams.access.revoke'),
  ('tournament_manager', 'tournaments.view'),
  ('tournament_manager', 'tournaments.manage'),
  ('tournament_manager', 'tournaments.groups.manage'),
  ('tournament_manager', 'tournaments.registration-settings.manage'),
  ('tournament_manager', 'tournaments.player-cards.manage'),
  ('content_manager', 'dashboard.view'),
  ('content_manager', 'content.view'),
  ('content_manager', 'content.create'),
  ('content_manager', 'content.edit'),
  ('content_manager', 'content.delete'),
  ('content_manager', 'content.publish'),
  ('content_manager', 'notifications.send'),
  ('shop_manager', 'dashboard.view'),
  ('shop_manager', 'shop.products.view'),
  ('shop_manager', 'shop.products.manage'),
  ('shop_manager', 'shop.orders.view'),
  ('shop_manager', 'shop.orders.manage'),
  ('viewer', 'dashboard.view'),
  ('viewer', 'matches.view'),
  ('viewer', 'stats.view'),
  ('viewer', 'rosters.view'),
  ('viewer', 'registrations.view'),
  ('viewer', 'teams.view'),
  ('viewer', 'tournaments.view'),
  ('viewer', 'content.view'),
  ('viewer', 'shop.products.view'),
  ('viewer', 'shop.orders.view'),
  ('viewer', 'admins.view'),
  ('viewer', 'audit.view')
on conflict do nothing;

do $$
declare
  role_count integer;
  permission_count integer;
  super_admin_permission_count integer;
begin
  select count(*) into role_count from public.admin_roles;
  select count(*) into permission_count from public.admin_permissions;

  if role_count <> 8 or permission_count <> 56 then
    raise exception 'RBAC seed validation failed: expected 8 roles and 56 permissions, found % roles and % permissions', role_count, permission_count;
  end if;

  select count(*) into super_admin_permission_count
  from public.admin_role_permissions rp
  join public.admin_permissions p on p.key = rp.permission_key
  where rp.role_key = 'super_admin';

  if super_admin_permission_count <> permission_count then
    raise exception 'RBAC seed validation failed: super_admin must have every catalog permission';
  end if;

  if exists (
    select 1
    from public.admin_role_permissions rp
    where rp.role_key = 'supervisor'
      and rp.permission_key in (
        'admins.create', 'admins.edit', 'admins.disable', 'admins.reset_password',
        'admins.permissions.manage', 'settings.manage', 'shop.orders.financial.manage'
      )
  ) then
    raise exception 'RBAC seed validation failed: supervisor has a forbidden permission';
  end if;
end
$$;

create index if not exists admin_profiles_role_key_idx on public.admin_profiles(role_key);
create index if not exists admin_profiles_is_active_idx on public.admin_profiles(is_active);
create index if not exists admin_permission_overrides_permission_idx on public.admin_permission_overrides(permission_key);
create index if not exists admin_audit_logs_actor_created_idx on public.admin_audit_logs(actor_user_id, created_at desc);
create index if not exists admin_audit_logs_entity_idx on public.admin_audit_logs(entity_type, entity_id, created_at desc);

do $$
declare
  v record;
  index_definition text;
begin
  for v in
    select * from (values
      ('admin_profiles_role_key_idx', 'admin_profiles', 'role_key'),
      ('admin_profiles_is_active_idx', 'admin_profiles', 'is_active'),
      ('admin_permission_overrides_permission_idx', 'admin_permission_overrides', 'permission_key'),
      ('admin_audit_logs_actor_created_idx', 'admin_audit_logs', 'actor_user_id,created_atdesc'),
      ('admin_audit_logs_entity_idx', 'admin_audit_logs', 'entity_type,entity_id,created_atdesc')
    ) as expected(index_name, table_name, key_definition)
  loop
    if to_regclass('public.' || v.index_name) is null then
      raise exception 'RBAC index validation failed: index % is missing', v.index_name;
    end if;

    select lower(regexp_replace(pg_get_indexdef(i.indexrelid), '[[:space:]]', '', 'g'))
    into index_definition
    from pg_index i
    where i.indexrelid = to_regclass('public.' || v.index_name)
      and i.indrelid = to_regclass('public.' || v.table_name)
      and i.indisvalid
      and not i.indisunique
      and i.indpred is null
      and i.indexprs is null;

    if index_definition is null
       or position('onpublic.' || v.table_name || 'usingbtree(' || v.key_definition || ')' in index_definition) = 0 then
      raise exception 'RBAC index validation failed: incompatible definition for index %', v.index_name;
    end if;
  end loop;
end
$$;

-- Bootstrap only the confirmed existing account. Abort instead of guessing if the
-- legacy profile shape is not exactly the expected single Fathy admin profile.
do $$
declare
  bootstrap_user_id constant uuid := '2dfd1ab1-1fe2-4024-91bc-b17103f524be';
  auth_user_count integer;
  profile_count integer;
begin
  select count(*) into profile_count
  from public.admin_profiles
  where user_id = bootstrap_user_id
    and lower(trim(display_name)) = 'fathy'
    and lower(trim(role)) = 'admin';

  if profile_count <> 1 then
    raise exception 'RBAC bootstrap aborted: confirmed admin profile did not match the expected identity; found %', profile_count;
  end if;

  if exists (
    select 1 from public.admin_profiles
    where user_id = bootstrap_user_id
      and lower(trim(display_name)) = 'fathy'
      and lower(trim(role)) = 'admin'
      and role_key is null
  ) then
    update public.admin_profiles
    set role_key = 'super_admin',
        is_active = true,
        updated_at = now()
    where role_key is null
      and user_id = bootstrap_user_id
      and lower(trim(display_name)) = 'fathy'
      and lower(trim(role)) = 'admin';
  elsif not exists (
    select 1 from public.admin_profiles
    where user_id = bootstrap_user_id
      and lower(trim(display_name)) = 'fathy'
      and lower(trim(role)) = 'admin'
      and role_key = 'super_admin'
      and is_active = true
  ) then
    raise exception 'RBAC bootstrap aborted: Fathy already has a conflicting role or inactive status';
  end if;

  select count(*) into auth_user_count
  from auth.users
  where id = bootstrap_user_id;

  select count(*) into profile_count
  from public.admin_profiles
  where user_id = bootstrap_user_id
    and lower(trim(display_name)) = 'fathy'
    and lower(trim(role)) = 'admin'
    and role_key = 'super_admin'
    and is_active = true;

  if auth_user_count <> 1 or profile_count <> 1 then
    raise exception 'RBAC bootstrap aborted: expected one verified Auth user and one active super_admin profile; found % Auth users and % profiles', auth_user_count, profile_count;
  end if;
end
$$;

-- RLS is enabled on the new RBAC tables with no client policies, so they remain
-- service-role-only. Do not change admin_profiles RLS or existing policies here:
-- their Production state was not available for read-only inspection.
alter table public.admin_roles enable row level security;
alter table public.admin_permissions enable row level security;
alter table public.admin_role_permissions enable row level security;
alter table public.admin_permission_overrides enable row level security;
alter table public.admin_audit_logs enable row level security;

do $$
begin
  if exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname in (
        'admin_roles', 'admin_permissions', 'admin_role_permissions',
        'admin_permission_overrides', 'admin_audit_logs'
      )
      and not c.relrowsecurity
  ) then
    raise exception 'RBAC RLS validation failed: row-level security is not enabled on every RBAC table';
  end if;

  if exists (
    select 1
    from pg_policy p
    where p.polrelid in (
      'public.admin_roles'::regclass,
      'public.admin_permissions'::regclass,
      'public.admin_role_permissions'::regclass,
      'public.admin_permission_overrides'::regclass,
      'public.admin_audit_logs'::regclass
    )
      and p.polcmd in ('*', 'a', 'w', 'd')
      and (0::oid = any(p.polroles) or p.polroles && array(
        select r.oid from pg_roles r where r.rolname in ('anon', 'authenticated')
      ))
  ) then
    raise exception 'RBAC RLS validation failed: client write policy exists on an RBAC table';
  end if;
end
$$;
